baseURL: "https://bsidesgrunn.org/"
languageCode: en-us
title: BSides Groningen
params:
  slogan: BSides Groningen is an Information Security conference organized by the community for the community.
  mastodon: "https://infosec.exchange/@bsidesgrunn"

menus:
  main:
    - name: Home
      url: "/"
      weight: 10
    - name: CFP
      url: "https://sessionize.com/bsidesgrunn"
      weight: 11
    - name: About
      url: "/about"
      weight: 20